### ISSUE TITLE
C# Track Courses to be Completed

### ISSUE THREAD

**Issue by GCarrell** [GCarrell/Treehouse#2]
## TODO

*Courses left to complete on the Treehouse C# Track*

* [ ] Intro to visual studio
* [ ] Using github with visual studio
* [ ] C# Basics
* [ ] C# Objects
* [ ] Intermediate C#
* [ ] C# Collections
* [ ] Unit testing in C#

👻
